In [2]:
# 분석
import pandas as pd
import numpy as np

# 시각화
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.colab'

In [ ]:
d_path = '/content/drive/MyDrive/Colab Notebooks/Dacon/'
X_train = pd.read_csv(d_path + 'train_features.csv')
y_train = pd.read_csv(d_path + 'train_labels.csv')
X_test = pd.read_csv(d_path + 'test_features.csv')
submission = pd.read_csv(d_path + 'sample_submission.csv')

display(X_train.head(3))
display(y_train.head(3))
display(X_test.head(3))

   id  time     acc_x     acc_y     acc_z      gy_x       gy_y       gy_z
0   0     0  1.206087 -0.179371 -0.148447 -0.591608 -30.549010 -31.676112
1   0     1  1.287696 -0.198974 -0.182444  0.303100 -39.139103 -24.927216
2   0     2  1.304609 -0.195114 -0.253382 -3.617278 -44.122565 -25.019629

   id  label                 label_desc
0   0     37  Shoulder Press (dumbbell)
1   1     26               Non-Exercise
2   2      3         Biceps Curl (band)

     id  time     acc_x     acc_y     acc_z       gy_x       gy_y       gy_z
0  3125     0 -0.628100 -0.160155  0.151487  49.665357  88.435961  13.597668
1  3125     1 -0.462548  0.012462 -0.053726  56.953059  96.185341  16.278458
2  3125     2 -0.363481 -0.091789 -0.130004  29.557396  93.836453  13.329043

In [4]:
X_train = pd.read_csv('train_features.csv')
y_train = pd.read_csv( 'train_labels.csv')
X_test = pd.read_csv('test_features.csv')
submission = pd.read_csv('sample_submission.csv')

In [5]:
X_pivot_train = pd.pivot_table(data = X_train, # X_train의 데이터를 통해서
                               values = X_train.columns[2:],  # id와 time을 제외한 피쳐를 대상으로
                               index = 'id', # id를 기준으로 잡아
                               aggfunc = ['sum','mean',         # 합, 평균
                                          'median','min','max', # 중앙값 최소값, 최대값
                                          'std','var'           # 베셀 보정 표본 표준편차, 비편향 편차 의 값을 구합니다.
                                         ]
                              )

X_pivot_test = pd.pivot_table(data = X_test, #
                               values = X_test.columns[2:], 
                               index = 'id', # id를 기준으로 잡아
                               aggfunc = ['sum','mean',        
                                          'median','min','max',
                                          'std','var'          
                                         ]
                              )

display(X_pivot_train.head(3))
display(X_pivot_test.head(3))

           sum                                                                 \
         acc_x       acc_y       acc_z         gy_x         gy_y         gy_z
id
0   558.797337 -131.082711 -222.252919 -1119.161589 -2015.703683   709.264425
1  -459.948117 -190.354639   -2.534051  6642.960123  1044.284884   835.976169
2    23.901616  -49.441742  375.607013 -5083.770868   358.725917  1831.974458

        mean                                 ...       std             \
       acc_x     acc_y     acc_z       gy_x  ...     acc_z       gy_x
id                                           ...
0   0.931329 -0.218471 -0.370422  -1.865269  ...  0.135131  13.284216
1  -0.766580 -0.317258 -0.004223  11.071600  ...  0.499395  79.244561
2   0.039836 -0.082403  0.626012  -8.472951  ...  0.248807  25.422926

                                var                                   \
          gy_y       gy_z     acc_x     acc_y     acc_z         gy_x
id
0    24.300479  25.275185  0.036664  0.031375  0.018260   176.470384
1    96.005289  75.545343  0.245548  0.113175  0.249396  6279.700472
2   118.956646  13.920337  0.506904  0.021646  0.061905   646.325142


            gy_y         gy_z
id
0     590.513292   638.834979
1    9217.015511  5707.098884
2   14150.683677   193.775778

[3 rows x 42 columns]

             sum                                                     \
           acc_x       acc_y       acc_z          gy_x         gy_y
id
3125 -611.238360  -11.744605 -139.355669  -1911.076959  1639.123438
3126 -313.705824  367.296809  -42.655405 -10644.915365  4184.863263
3127  304.167948  542.291164  -84.658968  -1307.846921 -1350.871152

                       mean                                 ...       std  \
             gy_z     acc_x     acc_y     acc_z       gy_x  ...     acc_z
id                                                          ...
3125 -1200.410049 -1.018731 -0.019574 -0.232259  -3.185128  ...  0.174672
3126 -2162.747150 -0.522843  0.612161 -0.071092 -17.741526  ...  0.383800
3127  -235.904841  0.506947  0.903819 -0.141098  -2.179745  ...  0.152077

                                            var                      \
           gy_x       gy_y       gy_z     acc_x     acc_y     acc_z
id
3125  12.897967  31.993022  12.251648  0.055806  0.008398  0.030510
3126  51.625096  45.706311  61.604867  0.291264  0.110899  0.147302
3127  22.770845  13.467885  23.041463  0.048371  0.036666  0.023128


             gy_x         gy_y         gy_z
id
3125   166.357553  1023.553453   150.102867
3126  2665.150566  2089.066820  3795.159662
3127   518.511372   181.383940   530.909012

[3 rows x 42 columns]

In [6]:
X_pivot_train.columns[:5]

MultiIndex([('sum', 'acc_x'),
            ('sum', 'acc_y'),
            ('sum', 'acc_z'),
            ('sum',  'gy_x'),
            ('sum',  'gy_y')],
           )

In [7]:
X_columns = [agg + '_' + column for agg,column in X_pivot_train.columns]
X_pivot_train.columns = X_columns
X_pivot_test.columns = X_columns
display(X_pivot_train.head())

,sum_acc_x,sum_acc_y,sum_acc_z,sum_gy_x,sum_gy_y,sum_gy_z,mean_acc_x,mean_acc_y,mean_acc_z,mean_gy_x,...,std_acc_z,std_gy_x,std_gy_y,std_gy_z,var_acc_x,var_acc_y,var_acc_z,var_gy_x,var_gy_y,var_gy_z
id,,,,,,,,,,,,,,,,,,,,,
0,558.797337,-131.082711,-222.252919,-1119.161589,-2015.703683,709.264425,0.931329,-0.218471,-0.370422,-1.865269,...,0.135131,13.284216,24.300479,25.275185,0.036664,0.031375,0.018260,176.470384,590.513292,638.834979
1,-459.948117,-190.354639,-2.534051,6642.960123,1044.284884,835.976169,-0.766580,-0.317258,-0.004223,11.071600,...,0.499395,79.244561,96.005289,75.545343,0.245548,0.113175,0.249396,6279.700472,9217.015511,5707.098884
2,23.901616,-49.441742,375.607013,-5083.770868,358.725917,1831.974458,0.039836,-0.082403,0.626012,-8.472951,...,0.248807,25.422926,118.956646,13.920337,0.506904,0.021646,0.061905,646.325142,14150.683677,193.775778
3,-532.621192,-52.600737,136.413976,10646.500409,2880.558352,-3521.938833,-0.887702,-0.087668,0.227357,17.744167,...,0.205882,42.928860,36.953466,23.647153,0.017134,0.037639,0.042387,1842.887012,1365.558625,559.187841
4,-395.410844,-202.240064,121.654507,-2891.782899,5791.027696,2672.029417,-0.659018,-0.337067,0.202758,-4.819638,...,0.389646,108.258866,60.514531,46.148326,0.245193,0.325247,0.151824,11719.982095,3662.008463,2129.668017

In [8]:
X_pivot_train = X_pivot_train.reset_index()
X_pivot_test = X_pivot_test.reset_index()

display(X_pivot_train.head())
display(X_pivot_test.head())

,id,sum_acc_x,sum_acc_y,sum_acc_z,sum_gy_x,sum_gy_y,sum_gy_z,mean_acc_x,mean_acc_y,mean_acc_z,...,std_acc_z,std_gy_x,std_gy_y,std_gy_z,var_acc_x,var_acc_y,var_acc_z,var_gy_x,var_gy_y,var_gy_z
0,0,558.797337,-131.082711,-222.252919,-1119.161589,-2015.703683,709.264425,0.931329,-0.218471,-0.370422,...,0.135131,13.284216,24.300479,25.275185,0.036664,0.031375,0.018260,176.470384,590.513292,638.834979
1,1,-459.948117,-190.354639,-2.534051,6642.960123,1044.284884,835.976169,-0.766580,-0.317258,-0.004223,...,0.499395,79.244561,96.005289,75.545343,0.245548,0.113175,0.249396,6279.700472,9217.015511,5707.098884
2,2,23.901616,-49.441742,375.607013,-5083.770868,358.725917,1831.974458,0.039836,-0.082403,0.626012,...,0.248807,25.422926,118.956646,13.920337,0.506904,0.021646,0.061905,646.325142,14150.683677,193.775778
3,3,-532.621192,-52.600737,136.413976,10646.500409,2880.558352,-3521.938833,-0.887702,-0.087668,0.227357,...,0.205882,42.928860,36.953466,23.647153,0.017134,0.037639,0.042387,1842.887012,1365.558625,559.187841
4,4,-395.410844,-202.240064,121.654507,-2891.782899,5791.027696,2672.029417,-0.659018,-0.337067,0.202758,...,0.389646,108.258866,60.514531,46.148326,0.245193,0.325247,0.151824,11719.982095,3662.008463,2129.668017

,id,sum_acc_x,sum_acc_y,sum_acc_z,sum_gy_x,sum_gy_y,sum_gy_z,mean_acc_x,mean_acc_y,mean_acc_z,...,std_acc_z,std_gy_x,std_gy_y,std_gy_z,var_acc_x,var_acc_y,var_acc_z,var_gy_x,var_gy_y,var_gy_z
0,3125,-611.238360,-11.744605,-139.355669,-1911.076959,1639.123438,-1200.410049,-1.018731,-0.019574,-0.232259,...,0.174672,12.897967,31.993022,12.251648,0.055806,0.008398,0.030510,166.357553,1023.553453,150.102867
1,3126,-313.705824,367.296809,-42.655405,-10644.915365,4184.863263,-2162.747150,-0.522843,0.612161,-0.071092,...,0.383800,51.625096,45.706311,61.604867,0.291264,0.110899,0.147302,2665.150566,2089.066820,3795.159662
2,3127,304.167948,542.291164,-84.658968,-1307.846921,-1350.871152,-235.904841,0.506947,0.903819,-0.141098,...,0.152077,22.770845,13.467885,23.041463,0.048371,0.036666,0.023128,518.511372,181.383940,530.909012
3,3128,-346.561617,-366.333946,18.891749,485.147442,-1790.981310,-14.590798,-0.577603,-0.610557,0.031486,...,0.326569,42.818157,45.069932,37.967372,0.186376,0.054569,0.106647,1833.394532,2031.298793,1441.521366
4,3129,-443.184021,109.521180,240.781103,-858.922755,865.419381,3447.298941,-0.738640,0.182535,0.401302,...,0.261848,92.301963,67.911174,43.353007,0.093512,0.098781,0.068565,8519.652350,4611.927587,1879.483194

In [9]:
X_pivot_train.shape

(3125, 43)

In [10]:
from lightgbm import LGBMClassifier
from sklearn.model_selection import train_test_split

In [11]:
ftr = X_pivot_train
target = y_train['label']

In [52]:
X_train, X_val, y_train, y_val = train_test_split(ftr, target, test_size=0.2, random_state=156)

lgbm_wrapper = LGBMClassifier(n_estimators=1000, num_leaves=100, subsample=0.8,
                      min_child_samples=320, max_depth=30)

evals = [(X_val, y_val)]
lgbm_wrapper.fit(X_train, y_train, early_stopping_rounds=100, eval_metric='logloss', eval_set=evals, verbose=True)
preds = lgbm_wrapper.predict(X_pivot_test)
pred_proba = lgbm_wrapper.predict_proba(X_pivot_test)[:,:]

[1]	valid_0's multi_logloss: 2.42704
Training until validation scores don't improve for 100 rounds
[2]	valid_0's multi_logloss: 2.23659
[3]	valid_0's multi_logloss: 2.07581
[4]	valid_0's multi_logloss: 1.94012
[5]	valid_0's multi_logloss: 1.82614
[6]	valid_0's multi_logloss: 1.73101
[7]	valid_0's multi_logloss: 1.64938
[8]	valid_0's multi_logloss: 1.57603
[9]	valid_0's multi_logloss: 1.51814
[10]	valid_0's multi_logloss: 1.46508
[11]	valid_0's multi_logloss: 1.41507
[12]	valid_0's multi_logloss: 1.37184
[13]	valid_0's multi_logloss: 1.32965
[14]	valid_0's multi_logloss: 1.29043
[15]	valid_0's multi_logloss: 1.25513
[16]	valid_0's multi_logloss: 1.22286
[17]	valid_0's multi_logloss: 1.19292
[18]	valid_0's multi_logloss: 1.16978
[19]	valid_0's multi_logloss: 1.14587
[20]	valid_0's multi_logloss: 1.12182
[21]	valid_0's multi_logloss: 1.10316
[22]	valid_0's multi_logloss: 1.08689
[23]	valid_0's multi_logloss: 1.06768
[24]	valid_0's multi_logloss: 1.05043
[25]	valid_0's multi_logloss: 1.0376
[26]	valid_0's multi_logloss: 1.02065
[27]	valid_0's multi_logloss: 1.00587
[28]	valid_0's multi_logloss: 0.998825
[29]	valid_0's multi_logloss: 0.985392
[30]	valid_0's multi_logloss: 0.975672
[31]	valid_0's multi_logloss: 0.969205
[32]	valid_0's multi_logloss: 0.961738
[33]	valid_0's multi_logloss: 0.954208
[34]	valid_0's multi_logloss: 0.9492
[35]	valid_0's multi_logloss: 0.944227
[36]	valid_0's multi_logloss: 0.937736
[37]	valid_0's multi_logloss: 0.932919
[38]	valid_0's multi_logloss: 0.927639
[39]	valid_0's multi_logloss: 0.924529
[40]	valid_0's multi_logloss: 0.917822
[41]	valid_0's multi_logloss: 0.917943
[42]	valid_0's multi_logloss: 0.911269
[43]	valid_0's multi_logloss: 0.906043
[44]	valid_0's multi_logloss: 0.905166
[45]	valid_0's multi_logloss: 0.901973
[46]	valid_0's multi_logloss: 0.898229
[47]	valid_0's multi_logloss: 0.897211
[48]	valid_0's multi_logloss: 0.89543
[49]	valid_0's multi_logloss: 0.895887
[50]	valid_0's multi_logloss: 0.892522
[51]	valid_0's multi_logloss: 0.891237
[52]	valid_0's multi_logloss: 0.89033
[53]	valid_0's multi_logloss: 0.891543
[54]	valid_0's multi_logloss: 0.891982
[55]	valid_0's multi_logloss: 0.891018
[56]	valid_0's multi_logloss: 0.891301
[57]	valid_0's multi_logloss: 0.890095
[58]	valid_0's multi_logloss: 0.887904
[59]	valid_0's multi_logloss: 0.888553
[60]	valid_0's multi_logloss: 0.888798
[61]	valid_0's multi_logloss: 0.889232
[62]	valid_0's multi_logloss: 0.890787
[63]	valid_0's multi_logloss: 0.889952
[64]	valid_0's multi_logloss: 0.889983
[65]	valid_0's multi_logloss: 0.890926
[66]	valid_0's multi_logloss: 0.893192
[67]	valid_0's multi_logloss: 0.893406
[68]	valid_0's multi_logloss: 0.895465
[69]	valid_0's multi_logloss: 0.897401
[70]	valid_0's multi_logloss: 0.900135
[71]	valid_0's multi_logloss: 0.902141
[72]	valid_0's multi_logloss: 0.906023
[73]	valid_0's multi_logloss: 0.908682
[74]	valid_0's multi_logloss: 0.909896
[75]	valid_0's multi_logloss: 0.91256
[76]	valid_0's multi_logloss: 0.914937
[77]	valid_0's multi_logloss: 0.918119
[78]	valid_0's multi_logloss: 0.920054
[79]	valid_0's multi_logloss: 0.920415
[80]	valid_0's multi_logloss: 0.923103
[81]	valid_0's multi_logloss: 0.924602
[82]	valid_0's multi_logloss: 0.924504
[83]	valid_0's multi_logloss: 0.927172
[84]	valid_0's multi_logloss: 0.931009
[85]	valid_0's multi_logloss: 0.932999
[86]	valid_0's multi_logloss: 0.934684
[87]	valid_0's multi_logloss: 0.936217
[88]	valid_0's multi_logloss: 0.93831
[89]	valid_0's multi_logloss: 0.941433
[90]	valid_0's multi_logloss: 0.942624
[91]	valid_0's multi_logloss: 0.948048
[92]	valid_0's multi_logloss: 0.951033
[93]	valid_0's multi_logloss: 0.953307
[94]	valid_0's multi_logloss: 0.957484
[95]	valid_0's multi_logloss: 0.960719
[96]	valid_0's multi_logloss: 0.964955
[97]	valid_0's multi_logloss: 0.969213
[98]	valid_0's multi_logloss: 0.974644
[99]	valid_0's multi_logloss: 0.977118
[100]	valid_0's multi_logloss: 0.980634
[101]	valid_0's multi_logloss: 0.98737
[102]	valid_0's multi_logloss: 0.990284
[103]	valid_0's multi_logloss: 0.996923
[104]	valid_0's multi_logloss: 1.00059
[105]	valid_0's multi_logloss: 1.00092
[106]	valid_0's multi_logloss: 1.00572
[107]	valid_0's multi_logloss: 1.00777
[108]	valid_0's multi_logloss: 1.01028
[109]	valid_0's multi_logloss: 1.01476
[110]	valid_0's multi_logloss: 1.01868
[111]	valid_0's multi_logloss: 1.02157
[112]	valid_0's multi_logloss: 1.02719
[113]	valid_0's multi_logloss: 1.02857
[114]	valid_0's multi_logloss: 1.03338
[115]	valid_0's multi_logloss: 1.03682
[116]	valid_0's multi_logloss: 1.04013
[117]	valid_0's multi_logloss: 1.04381
[118]	valid_0's multi_logloss: 1.04736
[119]	valid_0's multi_logloss: 1.05247
[120]	valid_0's multi_logloss: 1.05595
[121]	valid_0's multi_logloss: 1.06188
[122]	valid_0's multi_logloss: 1.06458
[123]	valid_0's multi_logloss: 1.07201
[124]	valid_0's multi_logloss: 1.07632
[125]	valid_0's multi_logloss: 1.07893
[126]	valid_0's multi_logloss: 1.08189
[127]	valid_0's multi_logloss: 1.08377
[128]	valid_0's multi_logloss: 1.08859
[129]	valid_0's multi_logloss: 1.09239
[130]	valid_0's multi_logloss: 1.0974
[131]	valid_0's multi_logloss: 1.09919
[132]	valid_0's multi_logloss: 1.10243
[133]	valid_0's multi_logloss: 1.10857
[134]	valid_0's multi_logloss: 1.11231
[135]	valid_0's multi_logloss: 1.11744
[136]	valid_0's multi_logloss: 1.11929
[137]	valid_0's multi_logloss: 1.12371
[138]	valid_0's multi_logloss: 1.12728
[139]	valid_0's multi_logloss: 1.13028
[140]	valid_0's multi_logloss: 1.13365
[141]	valid_0's multi_logloss: 1.13863
[142]	valid_0's multi_logloss: 1.14358
[143]	valid_0's multi_logloss: 1.1478
[144]	valid_0's multi_logloss: 1.15074
[145]	valid_0's multi_logloss: 1.15539
[146]	valid_0's multi_logloss: 1.16115
[147]	valid_0's multi_logloss: 1.16388
[148]	valid_0's multi_logloss: 1.16748
[149]	valid_0's multi_logloss: 1.17113
[150]	valid_0's multi_logloss: 1.17262
[151]	valid_0's multi_logloss: 1.17588
[152]	valid_0's multi_logloss: 1.17997
[153]	valid_0's multi_logloss: 1.18304
[154]	valid_0's multi_logloss: 1.18923
[155]	valid_0's multi_logloss: 1.19502
[156]	valid_0's multi_logloss: 1.19667
[157]	valid_0's multi_logloss: 1.19908
[158]	valid_0's multi_logloss: 1.20416
Early stopping, best iteration is:
[58]	valid_0's multi_logloss: 0.887904

In [53]:
print(pred_proba.shape)

(782, 61)

In [54]:
submission.iloc[:,1:] = pred_proba
submission

,id,0,1,2,3,4,5,6,7,8,...,51,52,53,54,55,56,57,58,59,60
0,3125,0.000032,0.000029,0.000089,0.000099,0.000366,0.000034,0.000258,0.000128,0.000112,...,0.015623,0.000283,0.001417,0.000556,0.000126,0.000101,0.000318,0.036569,0.000020,0.000701
1,3126,0.000209,0.000105,0.000251,0.000323,0.000153,0.000046,0.000169,0.000108,0.000142,...,0.000088,0.000010,0.000173,0.000193,0.000131,0.000362,0.000192,0.000120,0.000031,0.001743
2,3127,0.001759,0.237799,0.000076,0.002137,0.000188,0.000296,0.001854,0.000936,0.008460,...,0.000166,0.000036,0.000405,0.003046,0.000350,0.005744,0.000123,0.000130,0.163438,0.009142
3,3128,0.005298,0.000233,0.000236,0.000119,0.000283,0.000063,0.000071,0.000444,0.000217,...,0.000034,0.000014,0.000567,0.000066,0.000106,0.000048,0.000038,0.000047,0.000026,0.003275
4,3129,0.011023,0.000081,0.000117,0.000193,0.000134,0.000040,0.000064,0.000092,0.001715,...,0.000047,0.000008,0.000060,0.000029,0.000046,0.000032,0.000221,0.000051,0.000022,0.000067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,3902,0.017285,0.000096,0.000123,0.000271,0.050739,0.000034,0.000080,0.000054,0.000469,...,0.001308,0.000076,0.000762,0.000055,0.000064,0.000090,0.000214,0.000076,0.000039,0.001781
778,3903,0.000614,0.000153,0.000058,0.000235,0.000180,0.000140,0.000132,0.000035,0.000180,...,0.000221,0.000028,0.000080,0.000038,0.000124,0.000056,0.000560,0.000026,0.000262,0.000271
779,3904,0.000497,0.000077,0.000030,0.000309,0.000021,0.000016,0.000045,0.000014,0.001481,...,0.000024,0.000004,0.000101,0.000012,0.000039,0.000022,0.000050,0.000014,0.000010,0.000368
780,3905,0.000940,0.002907,0.000238,0.000235,0.000052,0.000069,0.007720,0.000350,0.001339,...,0.000713,0.000027,0.000350,0.003296,0.000290,0.000918,0.000073,0.000205,0.000897,0.001062
781,3906,0.000175,0.000080,0.000025,0.000105,0.000017,0.000023,0.000028,0.000049,0.000192,...,0.000018,0.000004,0.000055,0.000021,0.000017,0.000025,0.000060,0.000038,0.000009,0.000960

In [55]:
submission.to_csv('baseline_rf.csv', index=False)